services:
  # PostgreSQL Database
  postgres:
    image: postgres:17
    container_name: ecom-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ecom-network

  # Redis Cache
  redis:
    image: redis:alpine
    container_name: ecom-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ecom-network

  # RabbitMQ Message Broker & Management UI
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecom-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"    # AMQP protocol
      - "15672:15672"  # Web Management UI (http://localhost:15672)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - ecom-network

  # Backend (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecom-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ecommerce
      JWT_SECRET: "supersecretkey123"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      REDIS_URL: redis://redis:6379
      GOOGLE_CLIENT_ID: 723393176190-guo4hjvurf35s1649hcd9tr44nir359o.apps.googleusercontent.com
      MAIL_FROM: patelchetram49@gmail.com
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 465
      MAIL_USER: patelchetram49@gmail.com
      MAIL_PASS: ubndgduyzyillzoq



    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ecom-network

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecom-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:4000
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: 723393176190-guo4hjvurf35s1649hcd9tr44nir359o.apps.googleusercontent.com
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - ecom-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  ecom-network:
    driver: bridge